language: python
python:
  - "2.7.3" # Ubuntu 12.4LTS (precise) and Debian 7 LTS (wheezy)
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"

jobs:
  include:
  - python: "3.7"
    dist: xenial  # https://github.com/travis-ci/travis-ci/issues/9069

# command to install dependencies
install:
  - pip install -r requirementsDEV.txt
# command to run tests
script:
  - coverage run functional_test.py
  - pytest --cov=./
